"""Threat intelligence feed ingestion.

Pulls SHA-256 hash lists from public feeds and appends them to the local
signature file. Runs on-demand via `update_all_feeds()` (wired to the CLI
and `/api/intel/update`).

Current feeds (ship out of the box):
    - AbuseCH MalwareBazaar full hash list (CSV)
    - AlienVault OTX: caller provides a pulse ID + API key

The network fetch uses only the stdlib. If a site is unreachable, the
feed is skipped and the operation is logged — we never partially corrupt
the signature file.
"""
from __future__ import annotations

import csv
import io
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

from deepsecurity.audit import audit_log
from deepsecurity.config import settings
from deepsecurity.logging_config import get_logger

_log = get_logger(__name__)


@dataclass
class FeedResult:
    name: str
    fetched: int
    added: int
    skipped: int
    error: str | None = None


def _read_existing(path: Path) -> set[str]:
    if not path.exists():
        return set()
    with path.open("r", encoding="utf-8") as f:
        return {
            line.strip().lower()
            for line in f
            if line.strip() and not line.strip().startswith("#")
        }


def _write_signatures(path: Path, hashes: set[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        f.write("# deepsecurity signature file — generated by threat_intel\n")
        for h in sorted(hashes):
            f.write(h + "\n")
    tmp.replace(path)  # atomic


def fetch_malwarebazaar(timeout: float = 30.0) -> FeedResult:
    """Full hash dump from AbuseCH MalwareBazaar (public, unauthenticated)."""
    url = "https://bazaar.abuse.ch/export/csv/full/"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:  # noqa: S310 — HTTPS
            raw = resp.read().decode("utf-8", errors="replace")
    except (urllib.error.URLError, TimeoutError) as exc:
        return FeedResult("malwarebazaar", 0, 0, 0, error=str(exc))

    # MalwareBazaar CSV: comma-separated, quoted, first row is a banner comment.
    hashes: set[str] = set()
    reader = csv.reader(io.StringIO(raw))
    for row in reader:
        if not row or row[0].startswith("#"):
            continue
        # Column 1 is sha256_hash
        if len(row) > 1:
            h = row[1].strip().strip('"').lower()
            if len(h) == 64 and all(c in "0123456789abcdef" for c in h):
                hashes.add(h)

    existing = _read_existing(settings.signature_path)
    added = hashes - existing
    final = existing | hashes
    _write_signatures(settings.signature_path, final)

    return FeedResult("malwarebazaar", len(hashes), len(added), len(hashes) - len(added))


def fetch_otx_pulse(pulse_id: str, api_key: str, timeout: float = 30.0) -> FeedResult:
    """Fetch a single AlienVault OTX pulse's file hashes by ID."""
    url = f"https://otx.alienvault.com/api/v1/pulses/{pulse_id}/indicators"
    req = urllib.request.Request(url, headers={"X-OTX-API-KEY": api_key})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310 — HTTPS
            import json as _json

            payload = _json.loads(resp.read().decode("utf-8"))
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        return FeedResult(f"otx:{pulse_id}", 0, 0, 0, error=str(exc))

    hashes: set[str] = set()
    for indicator in payload.get("results", []):
        if indicator.get("type") in {"FileHash-SHA256"}:
            h = indicator.get("indicator", "").strip().lower()
            if len(h) == 64:
                hashes.add(h)

    existing = _read_existing(settings.signature_path)
    added = hashes - existing
    final = existing | hashes
    _write_signatures(settings.signature_path, final)
    return FeedResult(
        f"otx:{pulse_id}", len(hashes), len(added), len(hashes) - len(added)
    )


def update_all_feeds(otx_pulses: list[tuple[str, str]] | None = None) -> list[FeedResult]:
    """Pull every configured feed. Returns per-feed results; never raises."""
    results: list[FeedResult] = []

    if settings.intel_malwarebazaar_enabled:
        res = fetch_malwarebazaar()
        results.append(res)
        audit_log(
            actor="system",
            action="intel.feed.malwarebazaar",
            status="error" if res.error else "ok",
            details={"fetched": res.fetched, "added": res.added, "error": res.error},
        )

    for pulse_id, api_key in otx_pulses or []:
        res = fetch_otx_pulse(pulse_id, api_key)
        results.append(res)
        audit_log(
            actor="system",
            action="intel.feed.otx",
            status="error" if res.error else "ok",
            details={"pulse_id": pulse_id, "fetched": res.fetched, "added": res.added},
        )

    # IP reputation is part of the same "intel refresh" operator intent.
    if settings.ip_reputation_enabled:
        from deepsecurity.ip_reputation import reputation as _rep

        rep_result = _rep.refresh()
        results.append(
            FeedResult(
                name="abuse.ch/feodotracker",
                fetched=rep_result.get("count", 0),
                added=rep_result.get("added", 0),
                skipped=0,
                error=rep_result.get("error"),
            )
        )

    return results
